### ISSUE TITLE
Não aparece o modal para editar o formulário

### ISSUE THREAD

**Issue by rg3915** [rg3915/jc-challenge#6]
@olivx me ajuda ai.
O problema deve ser na linha 44
https://github.com/rg3915/jc-challenge/blob/master/myproject/core/static/js/apps.js#L44

**Comment by olivx** [comment]
Regis troca isso...  
 $('.js-company-update').click(loadForm);
por isso
$('#company-table').on('click', '.js-company-update', loadForm);

esse botão não existe quando o html é carregado, por o evento click não vai detectar , 
precisa ser no on('click' , 'class', function);

mesma logica aqui...  
$('#company-table').on('click', '.js-company-delete', loadForm);
